# Generated by Django 4.2.8 on 2025-12-11 05:33

from django.db import migrations, models
import django.db.models.deletion
import tracks.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("campaigns", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Track",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("original_filename", models.CharField(max_length=255)),
                ("file", models.FileField(upload_to=tracks.models.track_upload_path)),
                (
                    "duration_seconds",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("file_size_bytes", models.BigIntegerField()),
                ("upload_date", models.DateField(auto_now_add=True, db_index=True)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "campaign",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tracks",
                        to="campaigns.campaign",
                    ),
                ),
            ],
            options={
                "db_table": "tracks",
                "ordering": ["-uploaded_at"],
            },
        ),
    ]
