# Generated by Django 4.2.8 on 2025-12-11 05:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tracks", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="track",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="tracks",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="track",
            index=models.Index(
                fields=["-uploaded_at"], name="tracks_uploade_c0ef0f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="track",
            index=models.Index(
                fields=["upload_date", "-uploaded_at"], name="tracks_upload__916f5f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="track",
            index=models.Index(
                fields=["user", "-uploaded_at"], name="tracks_user_id_9aea79_idx"
            ),
        ),
    ]
