# Generated by Django 4.2.8 on 2025-12-11 05:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "timestamp_seconds",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Position in track where comment is made (in seconds)",
                        max_digits=10,
                    ),
                ),
                ("comment_text", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "comments",
                "ordering": ["timestamp_seconds", "created_at"],
            },
        ),
    ]
